
FROM golang:1.21 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /catgpt
EXPOSE 8080
CMD [ "/catgpt" ]
FROM gcr.io/distroless/static-debian12:latest-amd64 AS release-stage
WORKDIR /
COPY --from=build-stage /catgpt /catgpt
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT [ "/catgpt" ]